name: Update Game IDs

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: |
          chmod +x update_json.sh
          ./update_json.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add game_ids.json current_index.txt
          git commit -m 'Update game ID'
          git push
